### ISSUE TITLE
RGB camera frame to event camera frame view point transformation

### ISSUE THREAD

**Issue by soikat15** [uzh-rpg/DSEC#11]
I hope you are doing fine. I want to thank you for providing such a large-scale event stereo dataset that contains events data from event cameras and standard RGB frames from the Blackfly cameras. 
I am interested to work with this amazing dataset. Hence, I start studying in detail about this dataset. While studying the dataset, I came to know about the two different stereo setups that were used to collect the event and RGB camera data . The resolution (640x480 vs 1440x1080) and the baseline (60cm vs 51cm) are different from the two cameras' stereo setup, I would be happy if you provide additional information/approach to solve the following issue. 

1. How to project / transform / map the frame cameras  frames to event cameras frame(left RGB frame -> left event camera, right RGB frame -> right event camera)  so that, the resolution and FOV will be the same (e.g., event camera such as DAVIS 346 provide event, as well as the standard camera frame, has the same FOV and resoution)

I am waiting for your valuable response.

**Comment by magehrig** [comment]
Hi @soikat15

In order to map the image data into the event camera coordinate frame you need the depth in the image coordinate frame. This can approximately be achieved via the following approach:

1)  computing the disparity from the rectified images
2) Use the intrinsic (camera model) and extrinsic parameters (stereo baseline) to project 3D points from disparity
3) project the 3D points into the event camera (rectified) coordinate frame

Although we designed the setup such the FOV of the cameras are similar, the overlap will not be perfect. Hence you will have some pixels in the event camera coordinate frame that have no corresponding point in the image coordinate frame. Your method will have to account for that.

Hope that helps

**Comment by magehrig** [comment]
Closing this issue as it is redundant with https://github.com/uzh-rpg/DSEC/issues/12
