### ISSUE TITLE
Question regarding optical flow GT

### ISSUE THREAD

**Issue by shiba24** [uzh-rpg/DSEC#27]
Hi authors,

thank you for providing the great dataset.
I have a couple of general questions regarding your optical flow. Sorry if it is noted or asked before.

1. (quick double-check) according to the [data format page](https://dsec.ifi.uzh.ch/data-format/), it is displacement, not the velocity. So it is basically `pix/100ms` values. My understanding is correct?
2. Only 18 training sequences out of 40+ have OF (for example, `zurich_city_00_a, b` etc does not have OF.) Is this intentional -  you don't have plan to release the GT for the rest of the sequences?
3. The training sequence file index is every 2, like `00002.png`, `00004.png`, etc. But the test sequence file index is every 10, like `820`, `830`, etc. Why is it so? Is there any difference of the time period of the displacement?

Shintaro

**Comment by magehrig** [comment]
Hi @shiba24 

You are welcome.
1. Yes, this is the displacement in 100ms steps. Measuring the accurate pixel velocity (infinitesimal) is not possible. This is why we provide displacements that more closely resemble what we can measure. Actually, there was at least one reviewer in the process that insisted on pixel velocities as what should be provided and estimated. It would be a nice paper to investigate the advantages/disadvantages of displacement vs. velocity estimation. However, you will not encounter a real-world dataset with accurate pixel velocity GT, that much I can guarantee :wink: 
2. Yes, only a subset has OF GT because we so far only managed to get GT for the static scenes of the dataset. It would be great to also get it for the dynamic objects but that is quite hard with the current data.
3. The reason is that the submission file size should not be excessively large. And a prediction at 500 ms is more than enough to approximate the error of evaluating at 100 ms. We actually checked that and the numbers were almost identical.

**Comment by shiba24** [comment]
Thank you for your quick reply! Following up on (3) - so, in case of the benchmark submission, you expect displacement per 100ms (not per 500ms ), and just evaluating them at 500ms intervals, right?

**Comment by magehrig** [comment]
Good question. yes, I will clarify this!

**Comment by shiba24** [comment]
Thank you!
