### ISSUE TITLE
Disparity between event and RGB camera

### ISSUE THREAD

**Issue by DeeperMind** [uzh-rpg/DSEC#6]
Hello, thank your for providing this awesome dataset!

My understanding is that the DSEC provides two sets of disparity, one between two RGB cameras, and another between two event cameras. I am just wondering whether the disparity between event camera and RGB camera is available, or could it be computed from camera intrinsics/extrinsics?

**Comment by magehrig** [comment]
You are welcome!

We rectified the event cameras and the RGB cameras respectively but not between event and RGB cameras. Therefore, this is not directly available. However, as you hypothesized, you can compute it from the available intrinsics and extrinsics. The best choice for this is probably to rectify the left event camera and right RGB camera (or left RGB camera and right event camera).

**Comment by DeeperMind** [comment]
Thank you for the reply! 
Could you offer more info about how such rectification can be achieved using the parameters from the calibration files?

**Comment by magehrig** [comment]
The calibration file format is documented here: https://github.com/uzh-rpg/DSEC#camera-calibration-file

From this, you can check if [opencv's stereoRectify](https://docs.opencv.org/4.5.2/d9/d0c/group__calib3d.html#ga617b1685d4059c6040827800e72ad2b6) works for you. I am not sure if this approach works due to the fact that event camera and RGB camera resolution is different. Otherwise, you can do it manually. Note that you have to use the rectified (without distortion) RGB intrinsics and extrinsics.
Once you know the rectification parameters you can use standard opencv functions to rectify the image according to the new rectification. In case of the event camera, you can use the following code to generate a rectification map:
```python
coords = np.stack(np.meshgrid(np.arange(width), np.arange(height))).reshape((2, -1)).astype("float32")
term_criteria = (cv2.TERM_CRITERIA_MAX_ITER | cv2.TERM_CRITERIA_EPS, 100, 0.001)
points = cv2.undistortPointsIter(coords, K, dist_coeffs, R_rect_unrect, K_rect, criteria=term_criteria)
inv_map = points.reshape((height, width, 2))
```
Hope that helps, good luck!

**Comment by magehrig** [comment]
There is currently no plan to provide also disparity GT between event and global shutter camera so I am closing this issue.
